name: Test Minimo
on:
  workflow_dispatch:
  push:
    branches: [develop]
jobs:
  prueba:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "Workflow funcionando correctamente"
# trigger
# retry sá., 21 de feb. de 2026 17:13:03
# test publico
# 1771712843
